Knoxite77 - Added Doku for s3 backend
knoxite/website pull request #37
Opened 2020-06-17 21:24 UTC by craftamap

2020-06-20 23:42 UTC, ma-hartma requested changes
Great documentation! I found two little improvements.

2020-06-20 23:42 UTC, ma-hartma commented on content/docs/storage-backends/content.md
> +for you Administrator (or really any other IAM-User with the right permissions).
Typo: your* instead of you

2020-06-20 23:42 UTC, ma-hartma commented on content/docs/storage-backends/content.md
> +As I do not want to set any tags, I just continue and press next again.
To keep the docs in "you"-view: If you do not want to set any tags, you can just continue and press next again.

2020-07-06 01:35 UTC, muesli approved these changes

2020-07-06 01:35 UTC, merged